with-expecter: true
packages:
  github.com/SyahrulBhudiF/Go_gRPC/internal/domain:
    config:
      all: true
      dir: internal/domain/mocks
      outpkg: mocks
      filename: "mock_{{.InterfaceName}}.go"